import React, { useState } from 'react';
import { StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';

const courses = [
  ['heart-outline', 'Ubuzima bw’imyororokere', 'Ubumenyi bwizewe ku mubiri, ubuzima n’isuku.'],
  ['people-outline', 'Imibanire n’itumanaho', 'Kubaka imibanire myiza, kubahana no kuvugana neza.'],
  ['happy-outline', 'Imibereho myiza', 'Kwita ku marangamutima, gufata ibyemezo no gushaka ubufasha bukwiye.'],
] as const;

export default function AdultEducationScreen({ onBack }: { onBack: () => void }) {
  const [unlocked, setUnlocked] = useState(false);

  if (!unlocked) {
    return <View><TouchableOpacity onPress={onBack} style={styles.back} activeOpacity={0.8}><Ionicons name="arrow-back" size={20} color="#2563EB" /><Text style={styles.backText}>Subira</Text></TouchableOpacity><View style={styles.gate}><View style={styles.lock}><Ionicons name="lock-closed" size={34} color="#7C3AED" /></View><Text style={styles.gateTitle}>Igice cy’abantu bakuru 18+</Text><Text style={styles.gateText}>Iki gice kigenewe abantu bafite imyaka 18 cyangwa irenga. Ibirimo ni iby’uburezi ku buzima n’imibanire, kandi ntibirimo ibintu by’urukozasoni.</Text><TouchableOpacity style={styles.primary} onPress={() => setUnlocked(true)} activeOpacity={0.85}><Text style={styles.primaryText}>Ndi 18+ · Komeza</Text></TouchableOpacity><TouchableOpacity onPress={onBack} activeOpacity={0.8}><Text style={styles.exit}>Subira ku masomo y’abana</Text></TouchableOpacity></View></View>;
  }

  return <View><TouchableOpacity onPress={onBack} style={styles.back} activeOpacity={0.8}><Ionicons name="arrow-back" size={20} color="#2563EB" /><Text style={styles.backText}>Subira</Text></TouchableOpacity><View style={styles.badge}><Ionicons name="lock-closed" size={15} color="#7C3AED" /><Text style={styles.badgeText}>18+ / Abakuru gusa</Text></View><Text style={styles.title}>Amasomo y’abakuru</Text><Text style={styles.subtitle}>Amasomo y’ubuzima n’imibanire atangwa mu buryo bw’uburezi, bwizewe kandi butuje.</Text><View style={styles.warning}><Ionicons name="shield-checkmark-outline" size={22} color="#7C3AED" /><Text style={styles.warningText}>Iki gice ntikigenewe konti z’abana. Ibirimo ni iby’uburezi gusa.</Text></View>{courses.map((course) => <TouchableOpacity key={course[1]} style={styles.card} activeOpacity={0.85}><View style={styles.icon}><Ionicons name={course[0]} size={23} color="#7C3AED" /></View><View style={{ flex: 1 }}><Text style={styles.cardTitle}>{course[1]}</Text><Text style={styles.cardText}>{course[2]}</Text></View><Ionicons name="chevron-forward" size={20} color="#94A3B8" /></TouchableOpacity>)}<Text style={styles.note}>Ku bibazo by’ubuzima, koresha amakuru aturuka ku nzego z’ubuzima zizewe cyangwa ubaze inzobere.</Text></View>;
}

const styles = StyleSheet.create({ back: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 18 }, backText: { color: '#2563EB', fontWeight: '700' }, gate: { backgroundColor: '#FFF', borderRadius: 24, padding: 24, alignItems: 'center', borderWidth: 1, borderColor: '#E2E8F0', marginTop: 12 }, lock: { width: 72, height: 72, borderRadius: 24, backgroundColor: '#F5F3FF', alignItems: 'center', justifyContent: 'center' }, gateTitle: { fontSize: 24, fontWeight: '900', color: '#0F172A', textAlign: 'center', marginTop: 18 }, gateText: { color: '#64748B', fontSize: 13, lineHeight: 20, textAlign: 'center', marginTop: 10 }, primary: { width: '100%', height: 52, borderRadius: 16, backgroundColor: '#7C3AED', alignItems: 'center', justifyContent: 'center', marginTop: 20 }, primaryText: { color: '#FFF', fontWeight: '900' }, exit: { color: '#2563EB', fontWeight: '700', marginTop: 17 }, badge: { alignSelf: 'flex-start', flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: '#F5F3FF', borderRadius: 20, paddingHorizontal: 11, paddingVertical: 7, marginBottom: 10 }, badgeText: { fontSize: 11, fontWeight: '800', color: '#6D28D9' }, title: { fontSize: 27, fontWeight: '800', color: '#0F172A' }, subtitle: { color: '#64748B', fontSize: 14, lineHeight: 20, marginTop: 6 }, warning: { backgroundColor: '#F5F3FF', borderRadius: 18, padding: 15, marginTop: 16, flexDirection: 'row', gap: 10 }, warningText: { flex: 1, color: '#5B21B6', fontSize: 12, lineHeight: 18 }, card: { backgroundColor: '#FFF', borderRadius: 18, padding: 15, marginTop: 11, borderWidth: 1, borderColor: '#E2E8F0', flexDirection: 'row', alignItems: 'center', gap: 11 }, icon: { width: 45, height: 45, borderRadius: 14, backgroundColor: '#F5F3FF', alignItems: 'center', justifyContent: 'center' }, cardTitle: { fontWeight: '800', color: '#0F172A' }, cardText: { fontSize: 11, color: '#64748B', lineHeight: 17, marginTop: 3 }, note: { fontSize: 11, color: '#64748B', lineHeight: 17, marginTop: 15 } });
