import React, { useEffect, useState } from 'react';
import { Alert, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import SuperIcon from '../components/SuperIcon';
import { getChildren, saveChildren } from '../services/storage';
import type { ChildProfile, LearningLevel } from '../types/models';
import { colors, radius, shadow } from '../theme';
const levels:{id:LearningLevel;label:string;accent:string}[]=[{id:'early',label:'1–3',accent:colors.coral},{id:'young',label:'4–6',accent:colors.warning},{id:'kids',label:'7–10',accent:colors.primary},{id:'teens',label:'11–15',accent:colors.purple}];
export default function ChildProfileScreen({parentId,onBack,onSelect}:{parentId:string;onBack:()=>void;onSelect?:(child:ChildProfile)=>void}){
 const [children,setChildren]=useState<ChildProfile[]>([]);const[name,setName]=useState('');const[birthYear,setBirthYear]=useState('');const[level,setLevel]=useState<LearningLevel>('kids');
 useEffect(()=>{void getChildren().then(all=>setChildren(all.filter(child=>child.parentId===parentId)));},[parentId]);
 const addChild=async()=>{const year=Number(birthYear);const currentYear=new Date().getFullYear();if(!name.trim()){Alert.alert('Izina rirakenewe','Andika izina rikoreshwa muri app.');return;}if(!Number.isInteger(year)||year<currentYear-16||year>currentYear){Alert.alert('Umwaka utari wo',`Shyiramo umwaka uri hagati ya ${currentYear-16} na ${currentYear}.`);return;}const child:ChildProfile={id:`child_${Date.now()}`,parentId,name:name.trim(),birthYear:year,level,avatar:'user',createdAt:new Date().toISOString()};const all=await getChildren();await saveChildren([...all,child]);setChildren(current=>[...current,child]);setName('');setBirthYear('');Alert.alert('Byakunze',`${child.name} yongewe muri konti.`);};
 return <View><TouchableOpacity onPress={onBack} style={styles.back}><SuperIcon name="arrow-back" size={19} color={colors.primary}/><Text style={styles.backText}>Subira</Text></TouchableOpacity><View style={styles.heading}><View><Text style={styles.kicker}>PARENT • PROFILES</Text><Text style={styles.title}>Abana banjye</Text><Text style={styles.subtitle}>Gucunga profile z’abana utabitse amakuru menshi adakenewe.</Text></View><View style={styles.headerIcon}><SuperIcon name="users" size={24} color={colors.primary}/></View></View>{children.map(child=><TouchableOpacity key={child.id} style={styles.child} onPress={()=>onSelect?.(child)} activeOpacity={0.86}><View style={styles.avatar}><SuperIcon name="user" size={22} color={colors.primary}/></View><View style={{flex:1}}><Text style={styles.childName}>{child.name}</Text><Text style={styles.childMeta}>Urwego: {levels.find(item=>item.id===child.level)?.label} • {child.birthYear}</Text></View><SuperIcon name="chevron-forward" size={18} color={colors.muted}/></TouchableOpacity>)}<View style={styles.form}><Text style={styles.formTitle}>Ongeramo umwana</Text><TextInput value={name} onChangeText={setName} placeholder="Izina" autoCapitalize="words" style={styles.input}/><TextInput value={birthYear} onChangeText={setBirthYear} placeholder="Umwaka w’amavuko" keyboardType="number-pad" style={styles.input}/><Text style={styles.label}>Urwego rw’imyaka</Text><View style={styles.levels}>{levels.map(item=><TouchableOpacity key={item.id} onPress={()=>setLevel(item.id)} style={[styles.level,level===item.id&&{backgroundColor:item.accent}]}><Text style={[styles.levelText,level===item.id&&styles.levelTextActive]}>{item.label}</Text></TouchableOpacity>)}</View><TouchableOpacity style={styles.button} onPress={()=>void addChild()}><SuperIcon name="plus" size={19} color="#FFF"/><Text style={styles.buttonText}>Ongeramo profile</Text></TouchableOpacity></View></View>;
}
const styles=StyleSheet.create({back:{flexDirection:'row',alignItems:'center',gap:6,marginBottom:19},backText:{color:colors.primary,fontWeight:'800'},heading:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},kicker:{fontSize:9,color:colors.primary,fontWeight:'900',letterSpacing:1.2},title:{fontSize:28,fontWeight:'900',color:colors.ink,marginTop:3},subtitle:{color:colors.muted,fontSize:11.5,lineHeight:18,marginTop:4,maxWidth:270},headerIcon:{width:52,height:52,borderRadius:17,backgroundColor:colors.primarySoft,alignItems:'center',justifyContent:'center'},child:{backgroundColor:colors.surface,borderRadius:18,padding:13,flexDirection:'row',alignItems:'center',gap:11,marginTop:11,borderWidth:1,borderColor:colors.border,...shadow.card},avatar:{width:46,height:46,borderRadius:15,backgroundColor:colors.primarySoft,alignItems:'center',justifyContent:'center'},childName:{fontSize:15,fontWeight:'900',color:colors.ink},childMeta:{color:colors.muted,marginTop:3,fontSize:10.5},form:{backgroundColor:colors.surface,borderRadius:20,padding:17,marginTop:15,borderWidth:1,borderColor:colors.border,...shadow.card},formTitle:{fontSize:17,fontWeight:'900',marginBottom:12,color:colors.ink},input:{height:52,borderWidth:1,borderColor:colors.border,borderRadius:14,paddingHorizontal:14,marginBottom:10,color:colors.ink,backgroundColor:'#FBFDFF'},label:{color:colors.text,fontWeight:'800',fontSize:11,marginTop:2,marginBottom:8},levels:{flexDirection:'row',gap:7,marginBottom:14},level:{flex:1,height:40,borderRadius:12,backgroundColor:'#F1F5F9',alignItems:'center',justifyContent:'center'},levelText:{fontWeight:'800',color:colors.text,fontSize:11},levelTextActive:{color:'#FFF'},button:{height:52,borderRadius:15,backgroundColor:colors.ink,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:7},buttonText:{color:'#FFF',fontWeight:'900',fontSize:13}});
