import React, { useEffect, useRef, useState } from 'react';
import { Animated, StyleSheet, Text, TouchableOpacity, useWindowDimensions, View } from 'react-native';
import SuperIcon from '../components/SuperIcon';
import { getLesson } from '../data/lessons';
import { saveProgress } from '../services/progress';
import type { ChildProfile } from '../types/models';
import { colors, radius, shadow } from '../theme';

type Props = { lessonId: string; child?: ChildProfile | null; onBack: () => void; onStartQuiz: () => void };

export default function LessonDetailScreen({ lessonId, child, onBack, onStartQuiz }: Props) {
  const {width}=useWindowDimensions();
  const lesson = getLesson(lessonId);
  const [step, setStep] = useState(0);
  const current = lesson.steps[step];
  const progressChildId = child?.id ?? 'local-child';
  const percent = Math.round(((step + 1) / lesson.steps.length) * 100);
  const enter=useRef(new Animated.Value(0)).current;
  useEffect(()=>{enter.setValue(0);Animated.timing(enter,{toValue:1,duration:280,useNativeDriver:true}).start()},[step,enter]);
  const next = async () => { try { await saveProgress({ childId: progressChildId, lessonId: lesson.id, progress: Math.max(10, Math.round(((step + 1) / lesson.steps.length) * 70)), completed: false, updatedAt: new Date().toISOString() }); } finally { if (step < lesson.steps.length - 1) setStep((value) => value + 1); else onStartQuiz(); } };
  return <View style={{width:'100%',maxWidth:Math.min(width-32,680),alignSelf:'center'}}>
    <TouchableOpacity onPress={onBack} style={styles.back} activeOpacity={0.8}><SuperIcon name="arrow-back" size={19} color={colors.primary} /><Text style={styles.backText}>Subira</Text></TouchableOpacity>
    <View style={styles.headerCard}><View style={styles.iconCircle}><SuperIcon name={lesson.icon} size={28} color="#FFF" /></View><View style={styles.headerCopy}><Text style={styles.subject}>{lesson.subject} · {lesson.duration}</Text><Text style={styles.title}>{lesson.title}</Text><Text style={styles.summary}>{lesson.summary}</Text></View></View>
    <View style={styles.progressRow}><Text style={styles.counter}>Igice {step + 1} / {lesson.steps.length}</Text><Text style={styles.percent}>{percent}%</Text></View><View style={styles.track}><View style={[styles.fill, { width: `${percent}%` }]} /></View>
    <View style={styles.media}><View style={styles.mediaArt}><View style={styles.sun}/><View style={styles.cloudOne}/><View style={styles.cloudTwo}/><View style={styles.mediaBook}><SuperIcon name="book-outline" size={31} color={colors.primary}/></View></View><View style={styles.mediaCaption}><SuperIcon name="play-circle" size={18} color={colors.primary}/><Text style={styles.mediaText}>Reba igishushanyo, soma ibisobanuro, hanyuma ukore imyitozo.</Text></View></View>
    <Animated.View style={[styles.lessonCard,{opacity:enter,transform:[{translateY:enter.interpolate({inputRange:[0,1],outputRange:[12,0]})}]}]}><View style={styles.stepIcon}><SuperIcon name={current.icon} size={25} color={colors.primary} /></View><Text style={styles.stepTitle}>{current.title}</Text><Text style={styles.stepText}>{current.text}</Text><View style={styles.tip}><SuperIcon name="bulb-outline" size={17} color="#9A6700" /><Text style={styles.tipText}>Soma neza, hanyuma gerageza kubivuga mu magambo yawe.</Text></View></Animated.View>
    <TouchableOpacity style={styles.primary} onPress={()=>void next()} activeOpacity={0.86}><Text style={styles.primaryText}>{step < lesson.steps.length - 1 ? 'Komeza' : 'Kora Quiz'}</Text><SuperIcon name="arrow-forward" size={19} color="#FFF" /></TouchableOpacity>
  </View>;
}
const styles = StyleSheet.create({ back: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 18 }, backText: { color: colors.primary, fontWeight: '800' }, headerCard: { backgroundColor: colors.primary, borderRadius: radius.xl, padding: 19, flexDirection: 'row', gap: 13, ...shadow.card }, iconCircle: { width: 58, height: 58, borderRadius: 18, backgroundColor: 'rgba(255,255,255,0.16)', alignItems: 'center', justifyContent: 'center' }, headerCopy: { flex: 1 }, subject: { color: '#DCEBFF', fontSize: 10.5, fontWeight: '800' }, title: { color: '#FFF', fontSize: 22, fontWeight: '900', marginTop: 4 }, summary: { color: '#EAF3FF', fontSize: 11.5, lineHeight: 18, marginTop: 5 }, progressRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 18 }, counter: { color: colors.text, fontWeight: '800', fontSize: 11 }, percent: { color: colors.primary, fontWeight: '900', fontSize: 11 }, track: { height: 7, backgroundColor: '#E6EEF7', borderRadius: 4, marginTop: 7, overflow: 'hidden' }, fill: { height: '100%', backgroundColor: colors.success, borderRadius: 4 }, media:{marginTop:14,borderRadius:20,overflow:'hidden',backgroundColor:'#EAF3FF',borderWidth:1,borderColor:'#D6E6F7'},mediaArt:{height:118,position:'relative',alignItems:'center',justifyContent:'center',overflow:'hidden'},sun:{position:'absolute',width:76,height:76,borderRadius:38,backgroundColor:'#FCD34D',right:22,top:-22},cloudOne:{position:'absolute',width:100,height:34,borderRadius:20,backgroundColor:'#FFF',left:12,bottom:18,opacity:.85},cloudTwo:{position:'absolute',width:82,height:30,borderRadius:20,backgroundColor:'#FFF',right:30,bottom:6,opacity:.75},mediaBook:{width:70,height:70,borderRadius:24,backgroundColor:'#FFF',alignItems:'center',justifyContent:'center',...shadow.card},mediaCaption:{minHeight:44,backgroundColor:colors.surface,paddingHorizontal:13,flexDirection:'row',alignItems:'center',gap:8},mediaText:{flex:1,fontSize:10.5,lineHeight:16,color:colors.text,fontWeight:'700'},lessonCard: { backgroundColor: colors.surface, borderRadius: radius.xl, padding: 20, marginTop: 14, borderWidth: 1, borderColor: colors.border, minHeight: 250, ...shadow.card }, stepIcon: { width: 50, height: 50, borderRadius: 16, backgroundColor: colors.primarySoft, alignItems: 'center', justifyContent: 'center' }, stepTitle: { fontSize: 21, fontWeight: '900', color: colors.ink, marginTop: 17 }, stepText: { color: '#52657F', fontSize: 14, lineHeight: 22, marginTop: 8 }, tip: { marginTop: 20, padding: 12, borderRadius: 14, backgroundColor: '#FFF7DF', flexDirection: 'row', gap: 8, alignItems: 'center' }, tipText: { flex: 1, color: '#8B6500', fontSize: 10.5, lineHeight: 16, fontWeight: '700' }, primary: { height: 55, borderRadius: 17, backgroundColor: colors.ink, marginTop: 14, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 9 }, primaryText: { color: '#FFF', fontWeight: '900', fontSize: 15 } });
