import React, { useState } from 'react';
import { Alert, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import SuperIcon from '../components/SuperIcon';
import { signInParent, signUpParent } from '../services/auth';
import { isSupabaseConfigured } from '../services/supabase';
import type { ParentAccount } from '../types/models';
import { colors, radius, shadow } from '../theme';
export default function ParentAuthScreen({onBack,onAuthenticated}:{onBack:()=>void;onAuthenticated:(parent:ParentAccount)=>void}){
 const [mode,setMode]=useState<'login'|'signup'>('signup'); const [name,setName]=useState(''); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [busy,setBusy]=useState(false);
 const submit=async()=>{if(busy)return;setBusy(true);try{const parent=mode==='signup'?await signUpParent(name,email,password):await signInParent(email,password);if(!parent){Alert.alert('Konti ntibonetse','Nta parent account ibonetse kuri iyi email.');return;}onAuthenticated(parent);}catch(error){Alert.alert('Ntibyashobotse',error instanceof Error?error.message:'Habaye ikibazo. Ongera ugerageze.');}finally{setBusy(false);}};
 return <View><TouchableOpacity onPress={onBack} style={styles.back}><SuperIcon name="arrow-back" size={19} color={colors.primary}/><Text style={styles.backText}>Subira</Text></TouchableOpacity><View style={styles.hero}><View style={styles.lock}><SuperIcon name="shield-checkmark-outline" size={28} color={colors.primary}/></View><Text style={styles.heroTitle}>{mode==='signup'?'Kora konti y’umubyeyi':'Injira nka Parent'}</Text><Text style={styles.heroText}>Konti y’umubyeyi icunga profile z’abana, imyigire n’umutekano.</Text></View>{mode==='signup'&&<TextInput value={name} onChangeText={setName} placeholder="Izina ry’umubyeyi" autoCapitalize="words" style={styles.input}/>}<TextInput value={email} onChangeText={setEmail} placeholder="Email" keyboardType="email-address" autoCapitalize="none" autoCorrect={false} style={styles.input}/><TextInput value={password} onChangeText={setPassword} placeholder="Ijambo ry’ibanga (nibura 8)" secureTextEntry style={styles.input}/><TouchableOpacity style={[styles.button,busy&&styles.disabled]} onPress={()=>void submit()} disabled={busy}><Text style={styles.buttonText}>{busy?'Tegereza...':mode==='signup'?'Kora konti':'Injira'}</Text><SuperIcon name="arrow-forward" size={18} color="#FFF"/></TouchableOpacity><TouchableOpacity onPress={()=>setMode(mode==='signup'?'login':'signup')} disabled={busy} style={styles.switch}><Text style={styles.switchText}>{mode==='signup'?'Mfite konti — Injira':'Nta konti mfite — Iyandikishe'}</Text></TouchableOpacity><View style={styles.info}><SuperIcon name={isSupabaseConfigured?'checkCircle':'sparkles'} size={17} color={isSupabaseConfigured?colors.success:colors.primary}/><Text style={styles.infoText}>{isSupabaseConfigured?'Supabase irakora. Authentication ikoreshwa kuri server.':'Demo mode: shyiramo Supabase env variables mbere yo kujya production.'}</Text></View></View>;
}
const styles=StyleSheet.create({back:{flexDirection:'row',alignItems:'center',gap:6,marginBottom:19},backText:{color:colors.primary,fontWeight:'800'},hero:{backgroundColor:colors.primarySoft,borderRadius:radius.xl,padding:19,borderWidth:1,borderColor:'#CFE4FF',...shadow.card},lock:{width:56,height:56,borderRadius:18,backgroundColor:colors.surface,alignItems:'center',justifyContent:'center'},heroTitle:{fontSize:25,fontWeight:'900',color:colors.ink,marginTop:15},heroText:{fontSize:12,lineHeight:19,color:colors.muted,marginTop:6},input:{height:54,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:15,paddingHorizontal:15,marginTop:11,fontSize:14,color:colors.ink},button:{height:55,borderRadius:17,backgroundColor:colors.primary,marginTop:13,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:10},disabled:{opacity:.6},buttonText:{color:'#FFF',fontWeight:'900',fontSize:15},switch:{alignItems:'center',paddingVertical:17},switchText:{color:colors.primary,fontWeight:'800',fontSize:12},info:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:16,padding:12,flexDirection:'row',gap:8,alignItems:'flex-start'},infoText:{flex:1,color:colors.muted,fontSize:10.5,lineHeight:16}});
