import React, { useEffect, useState } from 'react';
import { StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import SuperIcon from '../components/SuperIcon';
import { getProgress, getQuizAttempts } from '../services/progress';
import { lessons } from '../data/lessons';
import { colors, radius, shadow } from '../theme';

export default function ProgressScreen({ onBack }: { onBack: () => void }) {
  const [progress, setProgress] = useState<Awaited<ReturnType<typeof getProgress>>>([]);
  const [attempts, setAttempts] = useState(0);
  useEffect(() => { let mounted = true; Promise.all([getProgress(), getQuizAttempts()]).then(([items, quizItems]) => { if (mounted) { setProgress(items); setAttempts(quizItems.length); } }); return () => { mounted = false; }; }, []);
  const progressFor = (lessonId: string) => progress.find((item) => item.lessonId === lessonId)?.progress ?? 0;
  const completed = progress.filter((item) => item.completed).length;
  const average = lessons.length ? Math.round(lessons.reduce((sum, lesson) => sum + progressFor(lesson.id), 0) / lessons.length) : 0;
  return <View><TouchableOpacity onPress={onBack} style={styles.back}><SuperIcon name="arrow-back" size={19} color={colors.primary}/><Text style={styles.backText}>Subira</Text></TouchableOpacity><View style={styles.heading}><View><Text style={styles.kicker}>UBUREZI • IMYIGIRE</Text><Text style={styles.title}>Iterambere ryanjye</Text><Text style={styles.subtitle}>Reba uko uri gutera imbere.</Text></View><View style={styles.headerIcon}><SuperIcon name="chart" size={25} color={colors.primary}/></View></View><View style={styles.stats}><View style={styles.stat}><SuperIcon name="book" size={19} color={colors.primary}/><Text style={styles.statValue}>{completed}</Text><Text style={styles.statLabel}>Amasomo</Text></View><View style={styles.stat}><SuperIcon name="quiz" size={19} color={colors.purple}/><Text style={styles.statValue}>{attempts}</Text><Text style={styles.statLabel}>Quiz</Text></View><View style={styles.stat}><SuperIcon name="sparkles" size={19} color={colors.warning}/><Text style={styles.statValue}>{average}%</Text><Text style={styles.statLabel}>Impuzandengo</Text></View></View><View style={styles.card}><View style={styles.cardHead}><Text style={styles.cardTitle}>Amasomo yawe</Text><Text style={styles.cardHint}>{completed}/{lessons.length} yarangiye</Text></View>{lessons.map((lesson)=>{const value=progressFor(lesson.id);return <View key={lesson.id} style={styles.subject}><View style={styles.row}><Text style={styles.name}>{lesson.subject}</Text><Text style={styles.percent}>{value}%</Text></View><Text style={styles.lesson}>{lesson.title}</Text><View style={styles.track}><View style={[styles.fill,{width:`${value}%`}]}/></View></View>;})}</View><View style={styles.goal}><View style={styles.goalIcon}><SuperIcon name="trophy" size={22} color={colors.warning}/></View><View style={{flex:1}}><Text style={styles.goalTitle}>Intego y’uyu munsi</Text><Text style={styles.goalText}>Kora isomo rimwe na quiz imwe.</Text></View><SuperIcon name="chevron-forward" size={18} color="#B08A21"/></View></View>;
}
const styles=StyleSheet.create({back:{flexDirection:'row',alignItems:'center',gap:6,marginBottom:19},backText:{color:colors.primary,fontWeight:'800'},heading:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},kicker:{fontSize:9,color:colors.primary,fontWeight:'900',letterSpacing:1.2},title:{fontSize:27,fontWeight:'900',color:colors.ink,marginTop:3},subtitle:{color:colors.muted,fontSize:12,marginTop:4},headerIcon:{width:52,height:52,borderRadius:17,backgroundColor:colors.primarySoft,alignItems:'center',justifyContent:'center'},stats:{flexDirection:'row',gap:10,marginTop:18},stat:{flex:1,backgroundColor:colors.surface,borderRadius:17,padding:12,borderWidth:1,borderColor:colors.border,...shadow.card},statValue:{fontSize:21,fontWeight:'900',color:colors.ink,marginTop:7},statLabel:{fontSize:10,color:colors.muted,marginTop:2},card:{backgroundColor:colors.surface,borderRadius:20,padding:17,marginTop:14,borderWidth:1,borderColor:colors.border,...shadow.card},cardHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:15},cardTitle:{fontSize:17,fontWeight:'900',color:colors.ink},cardHint:{fontSize:10,color:colors.muted,fontWeight:'700'},subject:{marginBottom:15},row:{flexDirection:'row',justifyContent:'space-between'},name:{fontWeight:'800',color:colors.text},percent:{fontWeight:'900',color:colors.primary},lesson:{fontSize:10.5,color:colors.muted,marginTop:3},track:{height:7,backgroundColor:'#E7EEF7',borderRadius:4,marginTop:7,overflow:'hidden'},fill:{height:'100%',backgroundColor:colors.success,borderRadius:4},goal:{backgroundColor:colors.warningSoft,borderRadius:18,padding:13,marginTop:12,flexDirection:'row',gap:10,alignItems:'center'},goalIcon:{width:43,height:43,borderRadius:14,backgroundColor:colors.surface,alignItems:'center',justifyContent:'center'},goalTitle:{fontWeight:'900',color:'#8B6500',fontSize:13},goalText:{fontSize:10.5,color:'#A16207',marginTop:3}});
