import React, { useState } from 'react';
import { StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import SuperIcon from '../components/SuperIcon';
import { completeLesson, saveQuizAttempt } from '../services/progress';
import { getLesson } from '../data/lessons';
import type { ChildProfile } from '../types/models';
import { colors, radius, shadow } from '../theme';

const questions = [
  { q: 'Ni iki 2 + 3 bingana?', answers: ['4', '5', '6'], correct: 1 },
  { q: 'Igikoresho gikoreshwa mu kwandika kuri mudasobwa ni iki?', answers: ['Keyboard', 'Speaker', 'Monitor'], correct: 0 },
  { q: 'Amazi ashobora guhinduka umwuka iyo ashyushye. Ibi byitwa iki?', answers: ['Gukonja', 'Guhumeka', 'Guhinduka umwuka'], correct: 2 },
];

type Props = { onBack: () => void; lessonId?: string; child?: ChildProfile | null };
export default function QuizScreen({ onBack, lessonId = 'math-counting-1', child }: Props) {
  const lesson = getLesson(lessonId); const [index, setIndex] = useState(0); const [score, setScore] = useState(0); const [picked, setPicked] = useState<number | null>(null); const [saved, setSaved] = useState(false); const finished = index >= questions.length; const question = questions[index]; const childId = child?.id ?? 'local-child';
  const finish = async (finalScore: number) => { await completeLesson(childId, lesson.id); await saveQuizAttempt({ id: `${Date.now()}-${lesson.id}`, childId, lessonId: lesson.id, score: finalScore, total: questions.length, completedAt: new Date().toISOString() }); setSaved(true); };
  if (finished) return <View><TouchableOpacity onPress={onBack} style={styles.back}><SuperIcon name="arrow-back" size={19} color={colors.primary}/><Text style={styles.backText}>Subira</Text></TouchableOpacity><View style={styles.result}><View style={styles.trophy}><SuperIcon name="trophy" size={42} color={colors.warning}/></View><Text style={styles.resultTitle}>Warakoze!</Text><Text style={styles.lessonName}>{lesson.title}</Text><Text style={styles.resultScore}>{score}/{questions.length}</Text><View style={styles.scorePill}><SuperIcon name="checkCircle" size={15} color={colors.success}/><Text style={styles.scorePillText}>{saved ? 'Amanota yabitswe' : 'Kubika amanota...'}</Text></View><Text style={styles.resultText}>Warangije quiz y’iri somo. Komeza kwiga kugira ngo wongere ubumenyi.</Text><TouchableOpacity style={styles.primary} onPress={onBack}><Text style={styles.primaryText}>Komeza kwiga</Text><SuperIcon name="arrowRight" size={18} color="#FFF"/></TouchableOpacity></View></View>;
  const choose = (answer: number) => { if (picked !== null) return; const nextScore = answer === question.correct ? score + 1 : score; setPicked(answer); if (answer === question.correct) setScore(nextScore); setTimeout(() => { const nextIndex = index + 1; setIndex(nextIndex); setPicked(null); if (nextIndex >= questions.length) void finish(nextScore); }, 450); };
  const percent = Math.round((index / questions.length) * 100);
  return <View><TouchableOpacity onPress={onBack} style={styles.back}><SuperIcon name="arrow-back" size={19} color={colors.primary}/><Text style={styles.backText}>Subira</Text></TouchableOpacity><View style={styles.heading}><View><Text style={styles.kicker}>QUIZ • {lesson.subject.toUpperCase()}</Text><Text style={styles.title}>{lesson.title}</Text></View><View style={styles.questionBadge}><Text style={styles.questionBadgeText}>{index + 1}/{questions.length}</Text></View></View><View style={styles.track}><View style={[styles.fill,{width:`${Math.max(percent,8)}%`}]}/></View><View style={styles.question}><Text style={styles.q}>{question.q}</Text>{question.answers.map((answer,i)=>{const correct=picked===i&&i===question.correct; const wrong=picked===i&&i!==question.correct; return <TouchableOpacity key={answer} disabled={picked!==null} onPress={()=>choose(i)} style={[styles.answer,correct&&styles.correct,wrong&&styles.wrong]} activeOpacity={0.86}><View style={[styles.radio,(correct||wrong)&&styles.radioSelected]}><Text style={[styles.letter,(correct||wrong)&&styles.letterSelected]}>{String.fromCharCode(65+i)}</Text></View><Text style={[styles.answerText,(correct||wrong)&&styles.answerTextSelected]}>{answer}</Text><SuperIcon name={picked===i?(i===question.correct?'checkCircle':'closeCircle'):'circleHelp'} size={20} color={(correct||wrong)?'#FFF':colors.muted}/></TouchableOpacity>;})}</View></View>;
}
const styles=StyleSheet.create({back:{flexDirection:'row',alignItems:'center',gap:6,marginBottom:19},backText:{color:colors.primary,fontWeight:'800'},heading:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},kicker:{fontSize:9,color:colors.primary,fontWeight:'900',letterSpacing:1.2},title:{fontSize:24,fontWeight:'900',color:colors.ink,marginTop:3},questionBadge:{paddingHorizontal:11,paddingVertical:8,borderRadius:12,backgroundColor:colors.primarySoft},questionBadgeText:{fontSize:11,fontWeight:'900',color:colors.primary},track:{height:8,backgroundColor:'#E6EEF7',borderRadius:4,marginTop:18,overflow:'hidden'},fill:{height:'100%',backgroundColor:colors.primary,borderRadius:4},question:{backgroundColor:colors.surface,borderRadius:radius.xl,padding:18,marginTop:16,borderWidth:1,borderColor:colors.border,...shadow.card},q:{fontSize:20,fontWeight:'900',color:colors.ink,lineHeight:28,marginBottom:17},answer:{minHeight:58,borderRadius:15,borderWidth:1,borderColor:colors.border,paddingHorizontal:12,marginBottom:10,flexDirection:'row',alignItems:'center',gap:10},radio:{width:31,height:31,borderRadius:10,backgroundColor:'#F3F6FA',alignItems:'center',justifyContent:'center'},radioSelected:{backgroundColor:'rgba(255,255,255,0.22)'},letter:{fontSize:11,fontWeight:'900',color:colors.text},letterSelected:{color:'#FFF'},answerText:{flex:1,fontWeight:'800',color:colors.text,fontSize:13},answerTextSelected:{color:'#FFF'},correct:{backgroundColor:colors.success,borderColor:colors.success},wrong:{backgroundColor:colors.coral,borderColor:colors.coral},result:{backgroundColor:colors.surface,borderRadius:radius.xl,padding:25,alignItems:'center',borderWidth:1,borderColor:colors.border,...shadow.card},trophy:{width:80,height:80,borderRadius:28,backgroundColor:colors.warningSoft,alignItems:'center',justifyContent:'center'},resultTitle:{fontSize:26,fontWeight:'900',color:colors.ink,marginTop:14},lessonName:{color:colors.muted,marginTop:4},resultScore:{fontSize:48,fontWeight:'900',color:colors.primary,marginTop:8},scorePill:{flexDirection:'row',alignItems:'center',gap:5,backgroundColor:colors.successSoft,borderRadius:99,paddingHorizontal:10,paddingVertical:6,marginTop:5},scorePillText:{fontSize:10,fontWeight:'900',color:colors.success},resultText:{color:colors.muted,textAlign:'center',marginTop:12,lineHeight:19,fontSize:12},primary:{height:53,borderRadius:16,backgroundColor:colors.ink,paddingHorizontal:25,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:8,marginTop:19},primaryText:{color:'#FFF',fontWeight:'900',fontSize:14}});
