import React, { useEffect, useRef, useState } from 'react';
import { Animated, StyleSheet, Text, TouchableOpacity, useWindowDimensions, View } from 'react-native';
import SuperIcon from '../components/SuperIcon';
import { completeLesson, saveQuizAttempt } from '../services/progress';
import { getLesson } from '../data/lessons';
import type { ChildProfile } from '../types/models';
import { colors, radius, shadow } from '../theme';

type Question={q:string;answers:string[];correct:number};
const quizBank:Record<string,Question[]>={
 'math-counting-1':[{q:'Ni iki 2 + 3 bingana?',answers:['4','5','6'],correct:1},{q:'Ni uwuhe mubare uza nyuma ya 7?',answers:['6','8','9'],correct:1},{q:'Ufite pome 5 ugaha inshuti 2. Hasigara zingahe?',answers:['2','3','4'],correct:1}],
 'math-addition-2':[{q:'4 + 2 bingana na?',answers:['5','6','7'],correct:1},{q:'3 + 5 bingana na?',answers:['7','8','9'],correct:1},{q:'10 + 4 bingana na?',answers:['12','13','14'],correct:2}],
 'science-plants-1':[{q:'Ni iki igihingwa gikenera kugira ngo gikure?',answers:['Amazi','Urubura gusa','Umucanga gusa'],correct:0},{q:'Ibimera byinshi bikenera iki?',answers:['Urumuri','Umwijima gusa','Nta mazi'],correct:0},{q:'Ni iki gishobora gufasha igihingwa kubaho?',answers:['Amazi n’urumuri','Telefoni','Televiziyo'],correct:0}],
 'science-water-2':[{q:'Amazi ashyushye cyane ashobora guhinduka iki?',answers:['Umwuka','Ibuye','Ubutaka'],correct:0},{q:'Amazi akonje cyane ashobora kuba iki?',answers:['Urubura','Umwuka gusa','Umucanga'],correct:0},{q:'Amazi ni ingenzi ku ki?',answers:['Ubuzima','Amabuye gusa','Ibikoresho gusa'],correct:0}],
 'ict-computer-1':[{q:'Internet ni iki?',answers:['Urusobe rw’ibikoresho bihujwe','Keyboard','Printer'],correct:0},{q:'Browser ikoreshwa iki?',answers:['Gusura imbuga','Gusukura mudasobwa','Gucapa impapuro gusa'],correct:0},{q:'Ni iki utagomba gusangiza umuntu utazi?',answers:['Ijambo ry’ibanga','Ibara ukunda','Isomo ukunda'],correct:0}],
 'ict-digital-safety-2':[{q:'Ijambo ry’ibanga rikwiye kuba rimeze rite?',answers:['Rikomeye kandi ry’ibanga','Risangizwe na bose','Ribe izina gusa'],correct:0},{q:'Iyo umuntu utazi agusabye amakuru bwite kuri internet ukora iki?',answers:['Ntuyamuhe kandi ubwire umubyeyi','Uyamuhe ako kanya','Uyashyire ahantu hose'],correct:0},{q:'Niba ubona ikintu kiguteza impungenge ukwiye?',answers:['Kubwira umubyeyi cyangwa umwarimu','Kukibika ibanga','Kuguha password'],correct:0}],
 'languages-reading-1':[{q:'Iyo usoma interuro, ukwiye gukora iki?',answers:['Gusoma no kumva igisobanuro','Kureba gusa inyuguti','Gusimbuka amagambo yose'],correct:0},{q:'Ni iki gifasha gusoma neza?',answers:['Gusoma buhoro no gusubiramo','Kwiruka mu magambo','Kutareba utumenyetso'],correct:0},{q:'Nyuma yo gusoma, ushobora gukora iki?',answers:['Gusobanura ibyo wasomye','Kwibagirwa byose','Gufunga igitabo gusa'],correct:0}],
 'languages-vocabulary-2':[{q:'Ijambo rishya uryiga ute?',answers:['Kumenya ibisobanuro no kurikoresha','Kuryandika gusa','Kutarireba'],correct:0},{q:'Ni iki gifasha kwibuka ijambo?',answers:['Kurikoresha mu nteruro','Kutarisubiramo','Kuryirengagiza'],correct:0},{q:'Subiramo amagambo mashya kugira ngo?',answers:['Uyibuke neza','Uyibagirwe','Uyihindure imibare'],correct:0}],
};
const fallback=quizBank['math-counting-1'];
type Props={onBack:()=>void;lessonId?:string;child?:ChildProfile|null};

export default function QuizScreen({onBack,lessonId='math-counting-1',child}:Props){
 const {width}=useWindowDimensions();
 const lesson=getLesson(lessonId);const questions=quizBank[lesson.id]??fallback;const[index,setIndex]=useState(0);const[score,setScore]=useState(0);const[picked,setPicked]=useState<number|null>(null);const[saved,setSaved]=useState(false);const[saveError,setSaveError]=useState(false);const feedback=useRef(new Animated.Value(0)).current;const resultScale=useRef(new Animated.Value(.9)).current;const finished=index>=questions.length;const childId=child?.id??'local-child';
 useEffect(()=>{if(finished)Animated.spring(resultScale,{toValue:1,useNativeDriver:true,speed:12,bounciness:7}).start()},[finished,resultScale]);
 const finish=async(finalScore:number)=>{try{await completeLesson(childId,lesson.id);await saveQuizAttempt({id:`${Date.now()}-${lesson.id}`,childId,lessonId:lesson.id,score:finalScore,total:questions.length,completedAt:new Date().toISOString()});setSaved(true)}catch{setSaveError(true)}};
 if(finished)return <Animated.View style={[styles.resultWrap,{transform:[{scale:resultScale}]}]}><TouchableOpacity onPress={onBack} style={styles.back} activeOpacity={0.8}><SuperIcon name="arrow-back" size={19} color={colors.primary}/><Text style={styles.backText}>Subira</Text></TouchableOpacity><View style={styles.result}><View style={styles.confetti}><View style={styles.trophy}><SuperIcon name="trophy" size={42} color={colors.warning}/></View></View><Text style={styles.resultTitle}>Warakoze!</Text><Text style={styles.lessonName}>{lesson.title}</Text><Text style={styles.resultScore}>{score}/{questions.length}</Text><View style={styles.scorePill}><SuperIcon name="checkmark-circle" size={15} color={colors.success}/><Text style={styles.scorePillText}>{saved?'Amanota yabitswe':saveError?'Amanota yabitswe kuri telefone':'Kubika amanota...'}</Text></View><Text style={styles.resultText}>{score===questions.length?'Watsinze neza cyane! Komeza uwo mwete.':'Warangije quiz. Subiramo isomo maze wongere ugerageze.'}</Text><TouchableOpacity style={styles.primary} onPress={onBack} activeOpacity={0.88}><Text style={styles.primaryText}>Komeza kwiga</Text><SuperIcon name="arrow-forward" size={18} color="#FFF"/></TouchableOpacity></View></Animated.View>;
 const question=questions[index];const choose=(answer:number)=>{if(picked!==null)return;const correct=answer===question.correct;const nextScore=correct?score+1:score;setPicked(answer);if(correct)setScore(nextScore);feedback.setValue(0);Animated.sequence([Animated.timing(feedback,{toValue:1,duration:150,useNativeDriver:true}),Animated.timing(feedback,{toValue:0,duration:280,useNativeDriver:true})]).start();setTimeout(()=>{const nextIndex=index+1;setIndex(nextIndex);setPicked(null);if(nextIndex>=questions.length)void finish(nextScore)},520)};const percent=Math.round(index/questions.length*100);const cardWidth=Math.min(width-32,620);
 return <View style={{width:'100%',maxWidth:cardWidth,alignSelf:'center'}}><TouchableOpacity onPress={onBack} style={styles.back} activeOpacity={0.8}><SuperIcon name="arrow-back" size={19} color={colors.primary}/><Text style={styles.backText}>Subira</Text></TouchableOpacity><View style={styles.heading}><View style={{flex:1}}><Text style={styles.kicker}>QUIZ • {lesson.subject.toUpperCase()}</Text><Text style={styles.title}>{lesson.title}</Text></View><View style={styles.questionBadge}><Text style={styles.questionBadgeText}>{index+1}/{questions.length}</Text></View></View><View style={styles.track}><View style={[styles.fill,{width:`${Math.max(percent,8)}%`}]}/></View><Animated.View style={[styles.feedback,{opacity:feedback,transform:[{translateY:feedback.interpolate({inputRange:[0,1],outputRange:[8,0]})}]}]}><Text style={styles.feedbackText}>{picked===question.correct?'Ni byo! 🎉':'Gerageza ukomeze! 💪'}</Text></Animated.View><View style={styles.question}><Text style={styles.q}>{question.q}</Text>{question.answers.map((answer,i)=>{const correct=picked===i&&i===question.correct;const wrong=picked===i&&i!==question.correct;return <TouchableOpacity key={answer} disabled={picked!==null} onPress={()=>choose(i)} style={[styles.answer,correct&&styles.correct,wrong&&styles.wrong]} activeOpacity={0.86}><View style={[styles.radio,(correct||wrong)&&styles.radioSelected]}><Text style={[styles.letter,(correct||wrong)&&styles.letterSelected]}>{String.fromCharCode(65+i)}</Text></View><Text style={[styles.answerText,(correct||wrong)&&styles.answerTextSelected]}>{answer}</Text><SuperIcon name={picked===i?(i===question.correct?'checkmark-circle':'close-circle'):'ellipse-outline'} size={20} color={(correct||wrong)?'#FFF':colors.muted}/></TouchableOpacity>})}</View></View>;
}
const styles=StyleSheet.create({resultWrap:{width:'100%'},back:{flexDirection:'row',alignItems:'center',gap:6,marginBottom:19},backText:{color:colors.primary,fontWeight:'800'},heading:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},kicker:{fontSize:9,color:colors.primary,fontWeight:'900',letterSpacing:1.2},title:{fontSize:24,fontWeight:'900',color:colors.ink,marginTop:3},questionBadge:{paddingHorizontal:11,paddingVertical:8,borderRadius:12,backgroundColor:colors.primarySoft},questionBadgeText:{fontSize:11,fontWeight:'900',color:colors.primary},track:{height:8,backgroundColor:'#E6EEF7',borderRadius:4,marginTop:18,overflow:'hidden'},fill:{height:'100%',backgroundColor:colors.primary,borderRadius:4},feedback:{alignSelf:'center',marginTop:9,backgroundColor:colors.successSoft,paddingHorizontal:12,paddingVertical:6,borderRadius:99},feedbackText:{color:'#166534',fontSize:10,fontWeight:'900'},question:{backgroundColor:colors.surface,borderRadius:radius.xl,padding:18,marginTop:10,borderWidth:1,borderColor:colors.border,...shadow.card},q:{fontSize:20,fontWeight:'900',color:colors.ink,lineHeight:28,marginBottom:17},answer:{minHeight:58,borderRadius:15,borderWidth:1,borderColor:colors.border,paddingHorizontal:12,marginBottom:10,flexDirection:'row',alignItems:'center',gap:10},radio:{width:31,height:31,borderRadius:10,backgroundColor:'#F3F6FA',alignItems:'center',justifyContent:'center'},radioSelected:{backgroundColor:'rgba(255,255,255,0.22)'},letter:{fontSize:11,fontWeight:'900',color:colors.text},letterSelected:{color:'#FFF'},answerText:{flex:1,fontWeight:'800',color:colors.text,fontSize:13},answerTextSelected:{color:'#FFF'},correct:{backgroundColor:colors.success,borderColor:colors.success},wrong:{backgroundColor:colors.coral,borderColor:colors.coral},result:{backgroundColor:colors.surface,borderRadius:radius.xl,padding:25,alignItems:'center',borderWidth:1,borderColor:colors.border,...shadow.card},confetti:{padding:4},trophy:{width:80,height:80,borderRadius:28,backgroundColor:colors.warningSoft,alignItems:'center',justifyContent:'center'},resultTitle:{fontSize:26,fontWeight:'900',color:colors.ink,marginTop:14},lessonName:{color:colors.muted,marginTop:4},resultScore:{fontSize:48,fontWeight:'900',color:colors.primary,marginTop:8},scorePill:{flexDirection:'row',alignItems:'center',gap:5,backgroundColor:colors.successSoft,borderRadius:99,paddingHorizontal:10,paddingVertical:6,marginTop:5},scorePillText:{fontSize:10,fontWeight:'900',color:colors.success},resultText:{color:colors.muted,textAlign:'center',marginTop:12,lineHeight:19,fontSize:12},primary:{height:53,borderRadius:16,backgroundColor:colors.ink,paddingHorizontal:25,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:8,marginTop:19},primaryText:{color:'#FFF',fontWeight:'900',fontSize:14}});
